config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    post 'like', to: 'likes#create', as: 'like'
    delete 'unlike', to: 'likes#destroy', as: 'unlike'

    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  get 'explore', to: 'explore#index', as: :explore

  resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
    member do
      post 'follow', to: 'follows#create', as: 'follow'
      post 'accept', to: 'follows#accept', as: 'accept_follow'
      delete 'reject', to: 'follows#reject', as: 'reject_follow'
      delete 'unfollow', to: 'follows#destroy', as: 'unfollow'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comments, dependent: :destroy

  # Follows that the user has initiated; People the user follows
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :follows, source: :following

  # Follows where the user is the receiver; People the user is followed by
  has_many :reverse_follows, class_name: 'Follow', foreign_key: :following_id, dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :user, presence: true


  def confirmed_followers
    followers.where(follows: { accepted: true })  # Only get accepted follows
  end

  def pending_followers
    followers.where(follows: { accepted: false })
  end

  def send_follow_request(other_profile)
    return if other_profile == self
    follows.create(following: other_profile) unless following?(other_profile)
  end

  def accept_follow_request(profile)
    follow = reverse_follows.find_by(follower: profile)
    follow&.accept
  end

  def reject_follow_request(profile)
    follow = reverse_follows.find_by(follower: profile)
    follow&.destroy
  end

  def unfollow(profile)
    follow = follows.find_by(following: profile)
    follow&.destroy
  end

   # Check if this profile is following another
  def following?(profile)
    followings.include?(profile)
  end

  # Check if this profile is followed by another
  def followed_by?(profile)
    confirmed_followers.include?(profile)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :check_profile!, except: [:show, :index]
  before_action :set_profile, only: [:show, :edit, :update]
  before_action :authorize_owner!, only: [:edit, :update]

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    @profile.avatar_url = gravatar_url(current_user.email)

    if @profile.save
      redirect_to root_path, notice: 'Account successfully created!'
      UserMailer.welcome_email(current_user).deliver_later
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: "Profile updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @posts = @profile.posts
  end

  def index
    @profiles = Profile.all
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def authorize_owner!
    unless @profile.user == current_user
      redirect_to @profile, alert: "You are not authorized to edit or update this profile."
    end
  end

  def profile_params
    params.require(:profile).permit(:name)
  end

  def gravatar_url(email, size = 200)
    email_hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{email_hash}?s=#{size}&d=identicon"
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_follow_button.html.erb
<% unless current_profile == profile %>
  <%# GROUP 1%>
  <% if current_profile.following?(profile) %>
    <% if profile.pending_followers.include?(current_profile) %>
      PENDING
      <%= button_to "Cancel", unfollow_profile_path(profile), method: :delete %>
    <% else %>
      <%= button_to "Unfollow", unfollow_profile_path(profile), method: :delete %>
    <% end %>
  <% else %>
    <% if current_profile.followed_by?(profile) %>
      <%= button_to "Follow back", follow_profile_path(profile), method: :post %>
    <% else %>
      <%= button_to "Follow", follow_profile_path(profile), method: :post %>
    <% end %>
  <% end %>

  <%# GROUP 2%>
  <% if current_profile.pending_followers.include?(profile) %>
    <%= button_to "Accept", accept_follow_profile_path(profile), method: :post %>
    <%= button_to "Reject", reject_follow_profile_path(profile), method: :delete %>
  <% end %>

<% end %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, class: 'form form--no-margin') do |f| %>
  <div class="form__group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form__input', placeholder: 'Your new name...' %>
  </div>

  <div>
    <%= f.submit class: 'btn btn--primary' %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div class="profile" id="<%= dom_id profile %>">
    
    <div class="profile__info">
      <%= image_tag profile.avatar_url, class: 'avatar' %>
      <span class="profile__name"><%= profile.name %></span>
    </div>
    <div class="profile__buttons">
      <%= render 'shared/follow_button', profile: profile %>
    </div>
</div>

app/views/profiles/edit.html.erb
<h1>Edit your Profile</h1><br>

<div class="avatar_container">
  <%= image_tag @profile.avatar_url, class: 'avatar avatar--large' %>
  <%= turbo_frame_tag "#{dom_id(@profile)}_form" do %>
    <%= render 'form', profile: @profile %>
  <% end %>
</div>

app/views/profiles/index.html.erb
<!-- No Link redirects here at the moment; Will add a redirect probably
from the home page later when I implement a separate home page -->

<div class="user-profiles-container stack">
  <h1>Users</h1>
  <div id="user_profiles" class="stack">
    <%= render @profiles %>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Create your Profile</h1>
<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div>

  <div class="avatar_container avatar_container--centered">
    <%= image_tag @profile.avatar_url, class: 'avatar avatar--large' %>
    <%= turbo_frame_tag "#{dom_id(@profile)}_form", class: 'avatar_container' do %>
      <h1 class="profile_name"><%= @profile.name %></h1>
      <%= link_to edit_profile_path(@profile), class: 'btn btn--light' do %>
        <i class="fa fa-pen"></i>
      <% end %>
    <% end %>
  </div>

  <br>
  <!-- Add Profile Bio and Profile Picture -->
  <%= render 'shared/follow_button', profile: @profile %>


  <div class="posts_container">
    <div id="user_posts">
      <%= render @posts %>
    </div>
  </div>
</div>