config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    post 'like', to: 'likes#create', as: 'like'
    delete 'unlike', to: 'likes#destroy', as: 'unlike'

    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  get 'explore', to: 'explore#index', as: :explore

  resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
    member do
      post 'follow', to: 'follows#create', as: 'follow'
      post 'accept', to: 'follows#accept', as: 'accept_follow'
      delete 'reject', to: 'follows#reject', as: 'reject_follow'
      delete 'unfollow', to: 'follows#destroy', as: 'unfollow'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post

  validates :profile, :post, :body, presence: true
  validates :body, length: { maximum: 250 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[destroy edit update]
  before_action :authorize_creator, only: %i[destroy edit update]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.profile = current_user.profile

    if @comment.save
      flash.now[:notice] = 'Commented successfully!'
    else
      flash.now[:alert] = 'Unable to comment.'
    end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to(@post) }
    end
  end

  def destroy
    if @comment&.destroy
      flash.now[:notice] = 'Comment successfully deleted!'
    else
      flash.now[:alert] = 'Unable to delete the comment.'
    end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to(@post) }
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash.now[:notice] = 'Comment updated successfully!'
      render @comment
    else
      flash.now[:alert] = 'Unable to update the comment.'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def authorize_creator
    redirect_back_or_to(@post) unless @comment.profile == current_user.profile
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <div id="<%= dom_id(comment) %>_container" class="comment">
    <p>
      <strong><%= link_to comment.profile.name, comment.profile, target: '_top' %></strong>
      <br>
      <%= comment.body %><br>
      <small><%= timeago(comment.created_at) %></small>
      
    </p>
    <% if comment.profile == current_user.profile %>
      <div class="comment__actions">
          <%= link_to edit_post_comment_path(comment.post, comment), data: { turbo_frame: dom_id(comment) }, class: 'btn btn--light' do %>
            <i class="fa fa-pen"></i>
          <% end %>

          <%= link_to post_comment_path(comment.post, comment), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: 'btn btn--light' do %>
            <i class="fa fa-trash"></i>
          <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], id: 'comment-box') do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comment-box">
    <%= form.label :body, 'Comment Body', class: 'hidden' %>
    <%= form.text_field :body, placeholder: 'Type your comment', required: true, class: "comment-box__input" %>
    <%= form.submit 'Comment', class: 'comment-box__submit btn btn--primary' %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend 'comments', partial: 'comments/comment', locals: { post: @post, comment: @comment } %>
<%= turbo_stream.replace 'comment-box', partial: 'comments/form', locals: { post: @post, comment: Comment.new } %>
<%= turbo_stream.replace 'flash', partial: 'layouts/flash' %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>
<%= turbo_stream.replace 'flash', partial: 'layouts/flash' %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= turbo_frame_tag dom_id @comment do %>
  <h4>Edit Comment</h4>
  <%= render "form", post: @post, comment: @comment %>
  <%= link_to "Cancel", @post %>
<% end %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>