config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    post 'like', to: 'likes#create', as: 'like'
    delete 'unlike', to: 'likes#destroy', as: 'unlike'

    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  get 'explore', to: 'explore#index', as: :explore

  resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
    member do
      post 'follow', to: 'follows#create', as: 'follow'
      post 'accept', to: 'follows#accept', as: 'accept_follow'
      delete 'reject', to: 'follows#reject', as: 'reject_follow'
      delete 'unfollow', to: 'follows#destroy', as: 'unfollow'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :profile

  has_many :comments, dependent: :destroy

  has_many_attached :images do |attachable|
    attachable.variant :small, resize_to_limit: [200, 200]
  end

  validates :images, content_type: { in: %w[image/png image/jpg image/jpeg], message: 'must be a PNG or JPG'},
    size: {less_than: 5.megabytes, message: 'should be less than 5 MB'}


  validates :profile, presence: true
  validates :body, allow_blank: true, length: { minimum: 2, maximum: 2000 }

  validate :text_or_images_present

  default_scope { order(created_at: :desc) }

  def self.from_user_and_followings(user_profile)
    following_ids = user_profile.follows.accepted.pluck(:following_id)
    where(profile_id: [user_profile.id] + following_ids)
  end

  def text_or_images_present
    if body.blank? && images.blank?
      errors.add(:base, "Post must have either text or images")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.from_user_and_followings(current_profile)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.create_post(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { multipart: true }, class: 'form') do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__group">
    <%= form.label :body, class: 'hidden' %>
    <%= form.text_area :body, class: 'form__input', placeholder: "What's on your mind?", size: 'x5', style:"resize:vertical;", data: { controller: 'textarea-autogrow' } %>
  </div>

  <div class="form__group" data-controller="image-upload" data-image-upload-preview-class="image-upload-area__image_preview">
    <%= form.label :images, "Add Pictures", class: 'hidden' %>
    <%= form.file_field :images, multiple: true, accept: 'image/png,image/jpg,image/jpeg', direct_upload: true, class: 'form__input hidden', data: { "image-upload-target": "input" } %>

    <div class="image-upload-area" data-action="click->image-upload#openFilePicker">
      <p class="image-upload-area__text">Add pictures</p>
    </div>

    <!-- Thumbnails for selected images -->
    <div class="image-upload-area__preview" data-image-upload-target="preview"></div>
  </div>

  <div class="alignment--align-content-right">
    <%= form.submit 'Post', class: 'btn btn--primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" id="<%= dom_id post %>" data-controller="clickable-link" data-url="<%= post_path(post) %>" data-action="click->clickable-link#handleClick">
  <p>
    <div class="avatar_container">
      <%= image_tag post.profile.avatar_url, width: '20rem', class: 'avatar' %>
      <strong><%= link_to post.profile.name, profile_path(post.profile) %></strong>
    </div>
    
    <% if post.body.present? %>
      <%= post.body %><br>
    <% end %>
    
    <% if post.images.attached? %>
      <div class="post__images photo-grid">
        <% post.images.each do |image| %>
          <%= image_tag image.variant(:small) %>
        <% end %>
      </div>
    <% end %>
    
    <span><em><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes' %></em></span>

    <div class="post__actions">
      <% if post.likers.include?(current_user.profile) %>
        <%= button_to post_unlike_path(post), method: :delete, class: 'btn btn--primary' do %>
          <i class="fa fa-thumbs-down"></i> Unlike
        <% end %>
      <% else%>
        <%= button_to post_like_path(post), method: :post, class: 'btn btn--primary' do %>
          <i class="fa fa-thumbs-up"></i> Like
        <% end %>
      <% end %>
    </div>
  </p>
</div>

app/views/posts/edit.html.erb
<%= link_to @post do %>
  <i class="fa fa-arrow-left"></i> Back
<% end %><br>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/index.html.erb
<div id="feed">
  <h1 class="feed__heading">Your Feed</h1>

  <div class="feed__posts">
    <%= render 'form', post: Post.new %>

    <div class="form-divider form-divider--thick">
      <div class="form-divider__line form-divider__line--thick"></div>
      <div class="form-divider__text">Explore</div>
      <div class="form-divider__line form-divider__line--thick"></div>
    </div>

    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= link_to posts_path do %>
  <i class="fa fa-arrow-left"></i> Back
<% end %><br>

<h1>New post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= link_to posts_path do %>
  <i class="fa fa-arrow-left"></i> Back
<% end %><br>


<%= render @post %>

<div>
  <div class="avatar_container">
    <%= link_to "Edit", edit_post_path(@post), class: 'btn btn--light' %>
    <%= button_to "Delete", @post, method: :delete, class: 'btn btn--light' %>
  </div>
</div>
<br>

<div class="comments-container">
  <h3>Comments</h3>
  <%= render 'comments/form', post: @post, comment: Comment.new %>
  <div id="comments" class="comments">
    <%= render @comments %>
  </div>
</div>