config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    post 'like', to: 'likes#create', as: 'like'
    delete 'unlike', to: 'likes#destroy', as: 'unlike'

    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  get 'explore', to: 'explore#index', as: :explore

  resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
    member do
      post 'follow', to: 'follows#create', as: 'follow'
      post 'accept', to: 'follows#accept', as: 'accept_follow'
      delete 'reject', to: 'follows#reject', as: 'reject_follow'
      delete 'unfollow', to: 'follows#destroy', as: 'unfollow'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/_flash.html.erb
<div id="alert" class="alert">
  <p id="alert__notice" class="alert__notice"><%= notice %></p>    
  <p id="alert__error" class="alert__error"><%= alert %></p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <h1>Socialite</h1>
  <div class="header__links">
    <%= link_to "Your Feed", posts_path, class: "btn" %>
    <%= link_to "Explore", explore_path, class: "btn" %>
    <%= link_to "New post", new_post_path, class: "btn btn--primary" %>
    <% if current_profile&.persisted? %>
      <%= link_to current_profile, class: "alignment--align-content-center-vertical" do %>
        <%= image_tag current_profile.avatar_url, class: 'avatar avatar--medium avatar--inline' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/73110e100d.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Temporary Inline CSS Used -->
    
    <%= render 'layouts/flash' %>

    <main class="container">
      <%= render 'layouts/header' %>

      <%= yield %>
    </main>
  </body>
</html>